
project_id = "okvsvrcphudxxrdonfvp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54327
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_change_confirmations = true
enable_phone_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_functions]
enabled = true
port = 54328

[functions.stripe-webhook]
verify_jwt = false

[functions.process-stripe-payment]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.test-stripe-webhook]
verify_jwt = false
