
-- Add impact_summary column to design_analysis table
ALTER TABLE design_analysis 
ADD COLUMN impact_summary jsonb;

-- Add impact_summary column to design_batch_analysis table  
ALTER TABLE design_batch_analysis
ADD COLUMN impact_summary jsonb;

-- Add comment to describe the impact_summary structure
COMMENT ON COLUMN design_analysis.impact_summary IS 'Structured impact summary with metrics, recommendations, and key insights generated by Claude AI';
COMMENT ON COLUMN design_batch_analysis.impact_summary IS 'Structured impact summary with metrics, recommendations, and key insights generated by Claude AI for batch analysis';
