// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okvsvrcphudxxrdonfvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rdnN2cmNwaHVkeHhyZG9uZnZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDc5MjksImV4cCI6MjA2NTA4MzkyOX0.a7NBOADiCD3vdkOlqitKTqZOF0Np7639mjBOp57_G-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);